# take base image of specific node version with extra slim operating system under the hood.
FROM node:14-alpine

# set default working directory inside image/container for our node project
WORKDIR /app

ENTRYPOINT [ "npm" ]